### PR TITLE
Cannot remove single quotes in this context, at least under emacs 27.2

### PR DESCRIPTION
**Pull request by matthewpersico**
Debugged this with PRZEMEK KRYGER at $job.

### CODE REVIEW

**Review by steve-downey — APPROVED** [review]
LGTM.

**Comment by pkryger** [comment]
Just for future reference: my understanding is that for some reason `use-package` requires quoted function symbols for `:bind`. Could it be that the map is not defined in the package processed 🤔. Anyway: quoting symbols allows everything to load correctly. To keep bindings consistent and to avoid similar issues in the future I will cut another PR shortly that converts all `:bind` arguments to use quoted function symbols.

**Comment by steve-downey** [comment]
use-package is documented not to:  
```elisp
(use-package ace-jump-mode
  :bind ("C-." . ace-jump-mode))
```  
https://jwiegley.github.io/use-package/keywords/#bind-bind

However, it may be a case where we're loading one of our keymaps and binding functions that haven't been loaded by use-package yet.

**Comment by pkryger** [comment]
> use-package is documented not to:
> 
> ```emacs-lisp
> (use-package ace-jump-mode
>   :bind ("C-." . ace-jump-mode))
> ```

That's why I went for the minimalistic approach in the first place.

> However, it may be a case where we're loading one of our keymaps and binding functions that haven't been loaded by use-package yet.

Which seems strange in this particular case as `git-gutter-fringe` does `require 'git-gutter` and functions come from the latter. Maybe because they are not `autoload`ed 🤔?

**Pull request merged**
