### PR TITLE
Add CI tests and bump minimum supported version to 26.1

### PR DESCRIPTION
**Pull request by pkryger**
I've came across this [CI  for Emacs](https://github.com/purcell/setup-emacs). Decided to give it a go. My goal was to have CI that covers three or four areas.

### First Start with a Default Configuration
 Just do a first start with a default `exordium`. This should always work, shouldn't it? 😝 (See `first-run.sh` file).

### Compile All elisp
Compile all `*.el` files in `modules`, `themes`, and `extensions`. For some reason, the `recompile-modules` is not compiling anything when running in with `-Q --batch` flags. I also  think it should fail on warnings, but the number of non-compileable files were just to big for me to fix them all in this stretch. If you think this functionality should be here on day one, please let me know in comments. (See `compile.sh` file)

### Run All Tests
 Run all tests in `*.t.el`. Pretty self explanatory, I guess...  (See `unit-tests.sh` file).

### Validate Real Life configurations.
The idea is simple: do a first start with preferences from a real world case, i.e. with `exordium-helm-everywhere`.

I thought briefly about of checking out my taps and run the `first-start.sh` on it. OFC this could and should be extended for other users.  OTOH this would make some changes much more difficult, as people could abandon their taps. What's more it could be testing same configuration multiple times. Also, there may be some scaleability  issues, as I'm not sure how much power of `github.com` farm we can use for free. Likely running the `first-start.sh` with taps should only happen on used-by-the-tap-owner Emacs version? But how we keep that in check?

Alternative approach could be to extract some of non-default options and create a synthetic tests to see how they play together. But then it could test non existing configurations that, should some packages and/or extensions interfere, would cause unnecessary headaches.

With either of the above approaches users could use similar CI setup to test their taps.

I'd really appreciate your feedback here 🥺.

### Miscellaneous
While working on it, I noticed that `use-package` only honours `:if`/`:when` after `:ensure`. That causes more packages to be installed than actually necessary. The firsts to cause me issues were `auto-complete` and `company`. I decided to refactor them,  so that each of values of `exordium-complete-mode` don't install the other's packages, define helper functions, etc. I think that going over other conditionally used packages can be done in a separate efforts.

I've also noticed that some of our default installed modules (i.e., `treemacs`) require Emacs 26.1 or higher. Since I don't recall any complains about`exordium` not starting due to that, I gather `exordium` is not used on older Emacses. After all 26.1 was released more than 2.5 years ago. For that reason I decided to bump the minimum supported version to 26.1. This renders the need for `linum`, `nlinum`, and `hlinum` redundant, hence remove it. Hope this is not something controversial 🤞.

### CODE REVIEW

**Comment by pkryger** [comment]
IDK why the CI has not been fired on a PR event, despite being declared in `tests.yml`. Perhaps, the contents of `.github` are scanned only `master` branch for this scenario 🤔?

Anyway, [here](https://github.com/pkryger/exordium/actions/runs/449026370) is an example run (on my fork it worked on non-`master` branch 🤷‍♂️)

**Comment by philippe-grenet** [comment]
That is cool. Give me a bit of time to test it myself. As for removal of old linums, that is fine with me.

**Comment by steve-downey** [comment]
As a matter of policy, I'm fine with 26 as minimum version. It's available and stable on all the platforms I need a full emacs environment on. AIX and SunOS might as well be embedded targets for all my workflows.

**Comment by philippe-grenet** [comment]
I tried your add-ci branch and the scripts (didn't spend much time on compilation.sh). Nice work. My 2 cents:
- Compile all modules: let's not worry about ELisp warnings. They are not that meaningful unfortunately.
- I wouldn't worry about user's taps either. I think the value of these unit tests is to make sure any change we make to Exordium doesn't break things. I assume that most taps introduce new functions or key bindings, as opposed to redefine/override Exordium functions. If anything, someone should be able to add their own taps into the testing script.

**Comment by pkryger** [comment]
Thank you @philippe-grenet and @steve-downey for taking time to review 🙏.

> * Compile all modules: let's not worry about ELisp warnings. They are not that meaningful unfortunately.

Did you mean just run `compilation.sh` but not set `byte-compile-error-on-warn` there? I can give it a try and if there's no or very few fix ups I can push to this PR. How does it sound?

> * I wouldn't worry about user's taps either. I think the value of these unit tests is to make sure any change we make to Exordium doesn't break things. I assume that most taps introduce new functions or key bindings, as opposed to redefine/override Exordium functions.

This is what I do.

> If anything, someone should be able to add their own taps into the testing script.

I can add my taps to this PR. That would cause them to be validated with changes in `exordium`. I guess that would result with a workflow more where the change is blocked if anything in downstream breaks (like we know from `dpkg`). In a worst case we can remove abandoned/problematic tests in a PR that fails to build with a tap. Any objections?

**Comment by philippe-grenet** [comment]
> Did you mean just run `compilation.sh` but not set `byte-compile-error-on-warn` there? I can give it a try and if there's no or very few fix ups I can push to this PR. How does it sound?

Give it a try...
 
> In a worst case we can remove abandoned/problematic tests in a PR that fails to build with a tap. Any objections?

No, sounds good to me. Thanks.

**Comment by pkryger** [comment]
It seems that both were quite easy to achieve. Even macOS was easy. I made a series of commits trying to leave rationale in them. Now I have to add this CI pipeline to my tap so I won't silently break `exordium` 🙃.

**Review by philippe-grenet — APPROVED** [review]

**Pull request merged**
