### PR TITLE
Add org-superstar to download list

### PR DESCRIPTION
**Pull request by steve-downey**
Yikes. Fixed the broken bullets problem without adding new module to the
download list. Why use-package is good. Qou Vide.

### CODE REVIEW

**Comment by steve-downey** [comment]
Merging without review because it's clearly broken.

**Comment by matthewpersico** [comment]
You're welcome. :-)

**Comment by steve-downey** [comment]
Yes, trying to fix the broken thing quickly made it even more broken. I should have known better. 

More evidence that getting the use-package branch merged would be better.

**Comment by steve-downey** [comment]
https://github.com/emacs-exordium/exordium/blob/master/init.el#L184
is the actual fixed version

**Pull request merged**
